namespace COOPAI.API.DTOs.DebtSegmentation;

public sealed record MonthlyDebtBucketTrendDto(
    string Bucket,
    string BucketLabel,
    int ContractCount,
    decimal OutstandingBalance);

public sealed record MonthlyPerformancePeriodDto(
    int PeriodYear,
    int PeriodMonth,
    string PeriodLabelThai,
    int ContractCount,
    int MemberCount,
    decimal? OpeningOutstanding,
    decimal? IncreaseDuringPeriod,
    decimal EndingOutstanding,
    decimal? OutstandingMovement,
    int? OpeningOutstandingContracts,
    int? NewOutstandingContracts,
    int? ReducedOutstandingContracts,
    int EndingOutstandingContracts,
    int PaidOffContracts,
    decimal? AmountDue,
    int UnknownAmountDueContractCount,
    decimal ActualPayment,
    decimal? PriorArrears,
    int PriorArrearsKnownContractCount,
    int PriorArrearsUnknownContractCount,
    decimal PriorAdvanceCredit,
    decimal AdvanceCreditApplied,
    decimal NewAdvanceCredit,
    decimal EndingAdvanceCredit,
    decimal DownPayment,
    decimal AdvancePayment,
    decimal PaymentToPriorArrears,
    decimal PaymentToCurrentDue,
    int EarlyPayoffCount,
    decimal EarlyPayoffAmount,
    int ExpiredPayoffCount,
    decimal ExpiredPayoffAmount,
    int UnclassifiedCount,
    decimal UnclassifiedAmount,
    int? PaidOffDuringMonthCount,
    decimal? PaidOffDuringMonthAmount,
    int NewContractCount,
    decimal? EndingArrears,
    int EndingArrearsUnknownContractCount,
    decimal CashReconciliationDifference,
    decimal LedgerReconciliationDifference,
    bool HistoricalClassificationComplete,
    IReadOnlyList<string> IncompleteReasons,
    IReadOnlyList<MonthlyDebtBucketTrendDto> DebtBuckets);

public sealed record MonthlyPerformanceTrendDto(
    bool Available,
    string Message,
    string? DebtSnapshotId,
    string? InstallmentSnapshotId,
    int? CalendarYear,
    DateOnly? FirstPeriod,
    DateOnly? LatestPeriod,
    IReadOnlyList<MonthlyPerformancePeriodDto> Months);
