// <auto-generated />
using System;
using COOPAI.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace COOPAI.API.Migrations
{
    [DbContext(typeof(CoopDbContext))]
    [Migration("20260819023205_AddPortfolioSnapshotV11")]
    partial class AddPortfolioSnapshotV11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("COOPAI.API.Models.Guarantor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoanContractId")
                        .HasColumnType("int");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("MemberNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoanContractId");

                    b.HasIndex("MemberId");

                    b.ToTable("Guarantors");
                });

            modelBuilder.Entity("COOPAI.API.Models.Import.ImportLoanRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ContractDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MemberNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("OverdueDays")
                        .HasColumnType("int");

                    b.Property<decimal>("PrincipalBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProfitBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RowNo")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBalance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ContractNo");

                    b.HasIndex("MemberNo");

                    b.ToTable("ImportLoanRecords");
                });

            modelBuilder.Entity("COOPAI.API.Models.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedRecords")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SuccessRecords")
                        .HasColumnType("int");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("COOPAI.API.Models.ImportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.ToTable("ImportLogs");
                });

            modelBuilder.Entity("COOPAI.API.Models.LoanContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedOfficerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ContractDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastFollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastFollowUpRemark")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("OverdueDays")
                        .HasColumnType("int");

                    b.Property<int>("PaidInstallmentCount")
                        .HasColumnType("int");

                    b.Property<decimal>("PrincipalBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProfitBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContractNo");

                    b.HasIndex("LoanTypeId");

                    b.HasIndex("MemberId");

                    b.ToTable("LoanContracts");
                });

            modelBuilder.Entity("COOPAI.API.Models.LoanPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoanContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrincipalBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProfitBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProfitPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TotalBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoanContractId");

                    b.ToTable("LoanPayments");
                });

            modelBuilder.Entity("COOPAI.API.Models.LoanType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LoanTypes");
                });

            modelBuilder.Entity("COOPAI.API.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GroupCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MemberNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberNo");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("COOPAI.API.Models.Portfolio.PortfolioSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<int>("BlockingErrorCount")
                        .HasColumnType("int");

                    b.Property<decimal>("ComponentDifference")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("int");

                    b.Property<int>("ExpiredContractCount")
                        .HasColumnType("int");

                    b.Property<int>("ExpiredOutstandingContractCount")
                        .HasColumnType("int");

                    b.Property<decimal>("ExpiredOutstandingTotal")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<int>("ExpiredPaidOffContractCount")
                        .HasColumnType("int");

                    b.Property<int>("InTermContractCount")
                        .HasColumnType("int");

                    b.Property<int>("InTermOutstandingContractCount")
                        .HasColumnType("int");

                    b.Property<int>("InTermPaidOffContractCount")
                        .HasColumnType("int");

                    b.Property<int>("MatchedCanonicalCount")
                        .HasColumnType("int");

                    b.Property<int>("MissingCanonicalCount")
                        .HasColumnType("int");

                    b.Property<int>("OutstandingContractCount")
                        .HasColumnType("int");

                    b.Property<int>("PaidOffContractCount")
                        .HasColumnType("int");

                    b.Property<int>("PlaceholderRowCount")
                        .HasColumnType("int");

                    b.Property<decimal>("PrincipalDifference")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("PrincipalOpening")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("PrincipalOutstanding")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("PrincipalRepayment")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("ProfitDifference")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("ProfitOpening")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("ProfitOutstanding")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("ProfitRepayment")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<int>("ShadowExcludedCount")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly?>("SourceDataThroughDate")
                        .HasColumnType("date");

                    b.Property<string>("SourceFileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("SourceFileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SourceRetrievedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int>("TotalContractCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDifference")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("TotalOpening")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("TotalOutstanding")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("TotalRepayment")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<int>("TotalSourceRows")
                        .HasColumnType("int");

                    b.Property<int>("UnresolvedMemberContractCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WarningRecordCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate", "Revision")
                        .IsUnique();

                    b.HasIndex("SourceType", "SourceFileHash");

                    b.HasIndex("Status", "AsOfDate");

                    b.ToTable("PortfolioSnapshots");
                });

            modelBuilder.Entity("COOPAI.API.Models.Portfolio.PortfolioSnapshotExclusion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("LoanContractId")
                        .HasColumnType("int");

                    b.Property<int>("PortfolioSnapshotId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("LoanContractId");

                    b.HasIndex("PortfolioSnapshotId", "LoanContractId", "ReasonCode")
                        .IsUnique();

                    b.ToTable("PortfolioSnapshotExclusions");
                });

            modelBuilder.Entity("COOPAI.API.Models.Portfolio.PortfolioSnapshotRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BalanceStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CanonicalMatchStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateOnly?>("ContractDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpireDate")
                        .HasColumnType("date");

                    b.Property<string>("InclusionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("LoanContractId")
                        .HasColumnType("int");

                    b.Property<string>("LoanTypePrefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("MemberMatchStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("NormalizedContractNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OpeningSide")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("PortfolioSnapshotId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrincipalOpening")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("PrincipalOutstanding")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("PrincipalRepayment")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("ProfitOpening")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("ProfitOutstanding")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("ProfitRepayment")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<string>("SourceRecordKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceRowKind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("TermStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("TotalOpening")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("TotalOutstanding")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("TotalRepayment")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<string>("WarningCodesJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("LoanContractId", "PortfolioSnapshotId");

                    b.HasIndex("PortfolioSnapshotId", "LoanTypePrefix");

                    b.HasIndex("PortfolioSnapshotId", "MemberId");

                    b.HasIndex("PortfolioSnapshotId", "NormalizedContractNo")
                        .IsUnique();

                    b.HasIndex("PortfolioSnapshotId", "TermStatus", "BalanceStatus");

                    b.ToTable("PortfolioSnapshotRecords");
                });

            modelBuilder.Entity("COOPAI.API.Models.Guarantor", b =>
                {
                    b.HasOne("COOPAI.API.Models.LoanContract", "LoanContract")
                        .WithMany("Guarantors")
                        .HasForeignKey("LoanContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COOPAI.API.Models.Member", null)
                        .WithMany("GuaranteedLoans")
                        .HasForeignKey("MemberId");

                    b.Navigation("LoanContract");
                });

            modelBuilder.Entity("COOPAI.API.Models.ImportLog", b =>
                {
                    b.HasOne("COOPAI.API.Models.ImportBatch", "ImportBatch")
                        .WithMany("ImportLogs")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("COOPAI.API.Models.LoanContract", b =>
                {
                    b.HasOne("COOPAI.API.Models.LoanType", "LoanType")
                        .WithMany("LoanContracts")
                        .HasForeignKey("LoanTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COOPAI.API.Models.Member", "Member")
                        .WithMany("LoanContracts")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanType");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("COOPAI.API.Models.LoanPayment", b =>
                {
                    b.HasOne("COOPAI.API.Models.LoanContract", "LoanContract")
                        .WithMany("LoanPayments")
                        .HasForeignKey("LoanContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanContract");
                });

            modelBuilder.Entity("COOPAI.API.Models.Portfolio.PortfolioSnapshotExclusion", b =>
                {
                    b.HasOne("COOPAI.API.Models.LoanContract", "LoanContract")
                        .WithMany()
                        .HasForeignKey("LoanContractId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("COOPAI.API.Models.Portfolio.PortfolioSnapshot", "PortfolioSnapshot")
                        .WithMany("Exclusions")
                        .HasForeignKey("PortfolioSnapshotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LoanContract");

                    b.Navigation("PortfolioSnapshot");
                });

            modelBuilder.Entity("COOPAI.API.Models.Portfolio.PortfolioSnapshotRecord", b =>
                {
                    b.HasOne("COOPAI.API.Models.LoanContract", "LoanContract")
                        .WithMany()
                        .HasForeignKey("LoanContractId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("COOPAI.API.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("COOPAI.API.Models.Portfolio.PortfolioSnapshot", "PortfolioSnapshot")
                        .WithMany("Records")
                        .HasForeignKey("PortfolioSnapshotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LoanContract");

                    b.Navigation("Member");

                    b.Navigation("PortfolioSnapshot");
                });

            modelBuilder.Entity("COOPAI.API.Models.ImportBatch", b =>
                {
                    b.Navigation("ImportLogs");
                });

            modelBuilder.Entity("COOPAI.API.Models.LoanContract", b =>
                {
                    b.Navigation("Guarantors");

                    b.Navigation("LoanPayments");
                });

            modelBuilder.Entity("COOPAI.API.Models.LoanType", b =>
                {
                    b.Navigation("LoanContracts");
                });

            modelBuilder.Entity("COOPAI.API.Models.Member", b =>
                {
                    b.Navigation("GuaranteedLoans");

                    b.Navigation("LoanContracts");
                });

            modelBuilder.Entity("COOPAI.API.Models.Portfolio.PortfolioSnapshot", b =>
                {
                    b.Navigation("Exclusions");

                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
